/**
 * Writes deploy/schema.sql: the whole database structure as one SQL file, built from the same
 * migrations the API runs. Use it to create the database by hand (psql -f deploy/schema.sql).
 *
 *   npm run schema:export -w @ujjwal/api
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { migrations } from '../db/migrations';

export function buildSchemaSql(): string {
  const parts = [
    '-- Ujjwal Reach database structure (PostgreSQL 14 or newer, UTF-8 database).',
    '-- Generated by `npm run schema:export -w @ujjwal/api` from apps/api/src/db/migrations.ts.',
    '-- Do not edit by hand: add a migration in the code and export again.',
    '--',
    '-- Run once on an EMPTY database:  psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f deploy/schema.sql',
    '-- The last lines record the migrations as applied, so the API does not run them again.',
    '',
    'BEGIN;',
    '',
    'CREATE TABLE IF NOT EXISTS schema_migrations (id text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());',
    '',
  ];
  for (const m of migrations) {
    parts.push(`-- migration ${m.id}`, m.sql.trim(), '');
  }
  parts.push(
    '-- record the migrations',
    `INSERT INTO schema_migrations (id) VALUES\n${migrations.map((m) => `  ('${m.id}')`).join(',\n')}\nON CONFLICT DO NOTHING;`,
    '',
    'COMMIT;',
    '',
  );
  return parts.join('\n');
}

if (process.argv[1] && /export-schema/.test(process.argv[1])) {
  const out = resolve(process.cwd(), '../../deploy/schema.sql');
  writeFileSync(out, buildSchemaSql());
  console.log(`Wrote ${out}`);
}
